[package]
name = "cpgrust"
version = "0.1.0"
edition = "2021"

[lib]
name = "cpgrust"
crate-type = ["cdylib"]
path = "lib.rs"

[dependencies]
# syn = { version = "2.0", features = ["full"] }
# serde = { version = "1.0", features = ["derive"] }
# serde_json = "1.0"
libc = "0.2"